[General]
SyntaxVersion=2
BeginHotkey=118
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=689799a9-02e6-4eb9-9209-00b093962679
Description=六七八
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 1598, 1244
Delay 464
LeftClick 1
MoveTo 2173, 1167
Delay 500
LeftClick 1
MoveTo 2170, 739
Delay 500
LeftClick 1
MoveTo 853, 1016
MoveTo 172, 251
Delay 500
LeftClick 1
'==========以上是按键精灵录制的内容==========

Delay 25000


'==========以下是按键精灵录制的内容==========
MoveTo 1614, 1236
MoveTo 1602, 1242
Delay 483
LeftClick 1
MoveTo 2179, 530
Delay 500
LeftClick 1
MoveTo 180, 253
Delay 500
LeftClick 1
'==========以上是按键精灵录制的内容==========



Delay 40000

'==========以下是按键精灵录制的内容==========
MoveTo 1607, 1258
MoveTo 1603, 1256
Delay 459
LeftClick 1
MoveTo 2184, 957
Delay 1584
LeftClick 1
MoveTo 168, 262
Delay 1561
LeftClick 1
'==========以上是按键精灵录制的内容==========
