[General]
SyntaxVersion=2
BeginHotkey=114
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=59d05f61-573c-41dd-aea9-213d51af8df2
Description=第二关
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 1208, 954
MoveTo 1219, 969
Delay 458
LeftClick 1
MoveTo 1136, 1082
Delay 1270
LeftClick 1
MoveTo 1047, 472
Delay 1482
LeftClick 1
MoveTo 946, 564
Delay 1104
LeftClick 1
MoveTo 1388, 471
Delay 1185
LeftClick 1
MoveTo 1284, 565
Delay 1041
LeftClick 1
MoveTo 1485, 1264
Delay 1465
LeftClick 1
MoveTo 1992, 806
Delay 3277
LeftClick 1
MoveTo 2079, 909
Delay 1091
LeftClick 1
MoveTo 1639, 805
Delay 1176
LeftClick 1
MoveTo 1747, 901
Delay 928
LeftClick 1
MoveTo 795, 810
Delay 1193
LeftClick 1
MoveTo 887, 903
Delay 808
LeftClick 1
MoveTo 455, 808
Delay 802
LeftClick 1
MoveTo 547, 898
Delay 992
LeftClick 1
MoveTo 1119, 1247
Delay 1505
LeftClick 1
MoveTo 1050, 471
Delay 1452
LeftClick 1
MoveTo 1143, 559
Delay 861
LeftClick 1
MoveTo 1393, 475
Delay 777
LeftClick 1
'==========以下是按键精灵录制的内容==========
MoveTo 1446, 575
MoveTo 1471, 566
Delay 544
LeftClick 1
'==========以上是按键精灵录制的内容==========
